### ISSUE TITLE
Renovation of osoc Facebook page

### ISSUE THREAD

**Issue by khushaliporwal** [osocnitt/osoc-activities#1]

**Comment by lovey257** [comment]
Create the link to the some useful videos .

**Comment by lovey257** [comment]
upload the photos of our coding event TECHNOFANIA'17.

**Comment by lovey257** [comment]
upload the photos of our coding event TECHNOFANIA'17.

**Comment by 205116050** [comment]
i have created the page.......
this is the link
https://www.facebook.com/OPEN-Source-OPEN-Community-1258185717603995/
