### ISSUE TITLE
Techno-fania'17

### ISSUE THREAD

**Issue by khushaliporwal** [osocnitt/osoc-activities#2]

**Comment by lovey257** [comment]
This is a coding event

**Comment by lovey257** [comment]
assign the code part to someone.

**Comment by 205116050** [comment]
i am handling the printing and publishing for the event

**Comment by 205116050** [comment]
posters of event
![blue02-1](https://cloud.githubusercontent.com/assets/25800572/23563008/e664b6d2-006a-11e7-8168-988abf376020.jpg)
![Uploading POSTERblue.jpg…]()

**Comment by lovey257** [comment]
make another poster & also design the  certificates .....

**Comment by 205116050** [comment]
its ok
![posterblue](https://cloud.githubusercontent.com/assets/25800572/23563158/747e6cd8-006b-11e7-9c7e-6e7f7c619e8d.jpg)

**Comment by 205116050** [comment]
certificates
![certificate -black](https://cloud.githubusercontent.com/assets/25800572/23563249/e0ccd10e-006b-11e7-978f-f9d37600913a.jpg)

**Comment by 205116050** [comment]
![orgnizer certificate - copy](https://cloud.githubusercontent.com/assets/25800572/23563269/f1122352-006b-11e7-98d6-23a8d310f791.jpg)

**Comment by lovey257** [comment]
video for advertisment is required here.....

**Comment by lovey257** [comment]
@205116050 
decide the prizes for the winners......

**Comment by VivekXess205116081** [comment]
i'm making video..........

**Comment by lovey257** [comment]
codes are created ....
tested & setted by me.....

**Comment by VivekXess205116081** [comment]
multiple choice question(MCQ) also...........

**Comment by 205116050** [comment]
1 st position-tshirt
![winner tshirt](https://cloud.githubusercontent.com/assets/25800572/23564297/ec21888e-006f-11e7-8ace-41d1af0fda4d.jpg)
2 nd postion-photo frame
3 rd position-pen.....

**Comment by khushaliporwal** [comment]
MCQ's work is done

**Comment by lovey257** [comment]
kya baat kr rhi h ....
hoooooooo.........
good awesome..........

**Comment by VivekXess205116081** [comment]
bdia yaar........

**Comment by khushaliporwal** [comment]
what about logo??

**Comment by 205116050** [comment]
kuch jyada ho rha h

**Comment by khushaliporwal** [comment]
yes

**Comment by 205116050** [comment]
delete kro sb

**Comment by lovey257** [comment]
check the questions from above link given 
i have made you the administrator

**Comment by khushaliporwal** [comment]
Event has been successfully done 
Now working on other issues.
